//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group1FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class finaltable
    {
        public string address { get; set; }
        public string username { get; set; }
        public string flagged { get; set; }
        public string comments { get; set; }
        public string timeofday { get; set; }
        public string narc { get; set; }
        public System.DateTime startsquat { get; set; }
        public string police { get; set; }
        public System.DateTime datereported { get; set; }
        public byte reportedtimes { get; set; }
    }
}
